package com.example.simon

import android.app.Application
import android.content.res.Configuration
import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioTrack
import androidx.activity.compose.BackHandler
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.wrapContentHeight
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin

sealed interface GameNavigationEvent {
    data object NavigateToScore : GameNavigationEvent
}

class GameViewModel(application: Application, private val savedStateHandle: SavedStateHandle) : AndroidViewModel(application) {
    // shared repository used to save completed games
    private val scoreRepository = (application as SimonApplication).scoreRepository

    // mutable sequences for current run:
    // - gameSequence: expected sequence generated by the app
    // - userSequence: sequence entered by the player
    private val userSequence = mutableStateListOf<Char>()
    private val gameSequence = mutableStateListOf<Char>()

    // index of the next expected character in gameSequence
    private var currentStep = 0
    // presentationStep tracks highlight/blank steps to resume sequence playback
    private var presentationStep = 0

    // guard to avoid multiple concurrent navigation/save requests
    private var isNavigatingToScore = false

    // isGameActive gates input and scoring for the current run
    // isGamePaused pauses presentation without resetting the run
    // isPresentingSequence blocks input while the sequence is animating
    // failed marks that the user input ended the run
    var isGameActive by mutableStateOf(false)
    var isGamePaused by mutableStateOf(false)
    var isPresentingSequence by mutableStateOf(false)
    var failed by mutableStateOf(false)

    // currently highlighted tile while presenting the sequence
    var highlightedChar by mutableStateOf<Char?>(null)

    // pauseFlow is observed by the presentation coroutine to pause delays
    // playbackJob runs sequence animation
    private val pauseFlow = MutableStateFlow(false)
    private var playbackJob: Job? = null
    private var inputFlashJob: Job? = null
    private val toneTracks: Map<Char, AudioTrack> = buildToneTracks()

    // internal event bus for one-off navigation events
    private val _navigationEvents = MutableSharedFlow<GameNavigationEvent>(extraBufferCapacity = 1)
    val navigationEvents: SharedFlow<GameNavigationEvent> = _navigationEvents.asSharedFlow()

    companion object {
        private const val KEY_GAME_SEQUENCE = "game_sequence"
        private const val KEY_USER_SEQUENCE = "user_sequence"
        private const val KEY_CURRENT_STEP = "current_step"
        private const val KEY_IS_GAME_ACTIVE = "is_game_active"
        private const val KEY_IS_GAME_PAUSED = "is_game_paused"
        private const val KEY_IS_PRESENTING_SEQUENCE = "is_presenting_sequence"
        private const val KEY_PRESENTATION_STEP = "presentation_step"
        private const val KEY_FAILED = "failed"

        private const val TILE_HIGHLIGHT_DURATION_MS = 420L
        private const val PAUSE_BETWEEN_TONES_MS = 50L
        private const val RESUME_PRESENTATION_DELAY_MS = 350L
        private const val TONE_SAMPLE_RATE = 44100
        private const val TONE_DURATION_MS = 420
        private const val NEXT_SEQUENCE_DELAY_MS = 800L
        private const val USER_INPUT_FLASH_MS = 420L
    }

    init {
        restoreStateFromSavedHandle()
    }

    override fun onCleared() {
        toneTracks.values.forEach { track -> track.release() }
        super.onCleared()
    }

    // read-only copies exposed to UI/composables
    fun getGameSequence(): List<Char> = gameSequence.toList()
    fun getUserSequence(): List<Char> = userSequence.toList()

    // starts a new run from a clean state and immediately presents round 1
    fun startGame() {
        currentStep = 0
        presentationStep = 0
        userSequence.clear()
        gameSequence.clear()
        isGameActive = true
        isPresentingSequence = true
        failed = false
        isGamePaused = false
        isNavigatingToScore = false
        resumeGame()
        nextRound()
    }

    // resets all gameplay state when leaving/restarting the game screen
    fun reset() {
        gameSequence.clear()
        userSequence.clear()
        stopPresentation()
        currentStep = 0
        presentationStep = 0
        isGameActive = false
        isGamePaused = false
        isPresentingSequence = false
        failed = false
        isNavigatingToScore = false
        saveStateToSavedHandle()
    }

    // handles a tile press from the player
    // correct  -> advance step/round
    // wrong    -> mark game as failed
    fun onColorPressed(char: Char) {
        if (!isGameActive || failed || isGamePaused || isPresentingSequence) {
            return
        }

        flashUserInput(char)
        playToneForChar(char)
        userSequence.add(char)
        if (isExpectedInput(char)) {
            currentStep++
            if (userSequence.size == gameSequence.size) {
                currentStep = 0
                userSequence.clear()
                nextRound(NEXT_SEQUENCE_DELAY_MS)
            } else {
                saveStateToSavedHandle()
            }
            return
        }

        isGameActive = false
        failed = true
        saveStateToSavedHandle()
    }

    // handles user request to leave game and go to score screen
    // sets a guard to avoid double navigation then saves a valid score
    // emits a one-off navigation event after persistence completes
    fun requestNavigateToScore() {
        if (isNavigatingToScore) return
        isNavigatingToScore = true

        stopPresentation()
        stopAllTonesNow()
        val score = buildScoreForCurrentGame()
        viewModelScope.launch {
            if (score != null) {
                scoreRepository.saveScore(score)
                userSequence.clear()
                saveStateToSavedHandle()
            }
            _navigationEvents.emit(GameNavigationEvent.NavigateToScore)
        }
    }

    // builds a score snapshot for the current run
    // returns null when the run is not in a state that should be saved
    private fun buildScoreForCurrentGame(): Score? {
        if (!isGameActive && !failed) return null
        if (isPresentingSequence && gameSequence.size == 1) return null
        if (gameSequence.isEmpty()) return null

        return Score(
            playedGameSequence = gameSequence.toList(),
            playedUserSequence = userSequence.toList(),
            maxCorrectSequence = (gameSequence.size - 1).coerceAtLeast(0),
            errorPosition = currentStep.coerceIn(0, gameSequence.size)
        )
    }

    private fun isExpectedInput(char: Char): Boolean {
        val expectedChar = gameSequence.getOrNull(currentStep) ?: return false
        return char == expectedChar
    }

    private fun nextRound(initialDelayMs: Long = 0L) {
        gameSequence.add(generateGameCharacter())
        presentationStep = 0
        saveStateToSavedHandle()
        presentSequence(initialDelayMs = initialDelayMs)
    }

    private fun generateGameCharacter(): Char {
        return when ((1..6).random()) {
            1 -> 'R'
            2 -> 'G'
            3 -> 'B'
            4 -> 'M'
            5 -> 'Y'
            else -> 'C'
        }
    }

    fun pauseGame() {
        isGamePaused = true
        pauseFlow.value = true
        saveStateToSavedHandle()
    }

    fun resumeGame() {
        isGamePaused = false
        pauseFlow.value = false
        saveStateToSavedHandle()
    }

    private fun stopPresentation() {
        playbackJob?.cancel()
        inputFlashJob?.cancel()
        highlightedChar = null
        isPresentingSequence = false
        presentationStep = 0
        saveStateToSavedHandle()
    }

    private fun presentSequence(startStep: Int = 0, initialDelayMs: Long = 0L) {
        playbackJob?.cancel()
        playbackJob = viewModelScope.launch {
            val totalSteps = gameSequence.size * 2
            if (totalSteps == 0) {
                isPresentingSequence = false
                presentationStep = 0
                highlightedChar = null
                saveStateToSavedHandle()
                return@launch
            }

            isPresentingSequence = true
            presentationStep = startStep.coerceIn(0, totalSteps)
            saveStateToSavedHandle()
            try {
                if (initialDelayMs > 0) {
                    pauseAwareDelay(initialDelayMs)
                }

                // before the char was set to null before the delay
                // when the user presses the last tile of a round, flashUserInput() sets highlightedChar = char,
                // but nextRound() immediately calls presentSequence(initialDelayMs = ....)
                // which would clear highlightedChar right away
                // so the “user click highlight” was barely visible or not visible at all
                highlightedChar = null
                saveStateToSavedHandle()
                stopAllTonesForRestart()

                var step = presentationStep
                while (step < totalSteps) {
                    awaitIfPaused()
                    presentationStep = step
                    saveStateToSavedHandle()

                    val index = step / 2
                    val c = gameSequence[index]
                    if (step % 2 == 0) {
                        highlightedChar = c
                        playToneForChar(c)
                        pauseAwareDelay(TILE_HIGHLIGHT_DURATION_MS)
                    } else {
                        highlightedChar = null
                        pauseAwareDelay(PAUSE_BETWEEN_TONES_MS)
                    }
                    step++
                }
            } finally {
                highlightedChar = null
                isPresentingSequence = false
                presentationStep = totalSteps
                saveStateToSavedHandle()
            }
        }
    }

    private fun flashUserInput(char: Char) {
        inputFlashJob?.cancel()
        inputFlashJob = viewModelScope.launch {
            highlightedChar = char
            delay(USER_INPUT_FLASH_MS)
            if (highlightedChar == char) {
                highlightedChar = null
            }
        }
    }

    private suspend fun awaitIfPaused() {
        pauseFlow.filter { paused -> !paused }.first()
    }

    private suspend fun pauseAwareDelay(totalMs: Long) {
        var remaining = totalMs
        while (remaining > 0) {
            awaitIfPaused()
            val step = min(remaining, 16L)
            delay(step)
            if (!pauseFlow.value) remaining -= step
        }
    }

    private fun playToneForChar(char: Char) {
        val track = toneTracks[char] ?: return
        stopAllTonesForRestart()
        track.playbackHeadPosition = 0
        track.play()
    }

    // these two methods converge to the same final state
    // sometimes when playing the tones some time I hear crackling noise (only tested on emulator)
    // this seems to happen more with the function track.pause() and less with track.stop()

    // one meaningful difference, that I found, are:
    // 1) hardware resources
    // - pause "keeps audio hardware acquired"
    // - stop "releases hardware for others to use"
    // 2) data in the buffer
    // - pause "keeps the data in the buffer"
    // - stop "continues playing the rest of the written buffer unless cleared"

    // from the AudioTrack stop() documentation:
    // https://developer.android.com/reference/android/media/AudioTrack.html#stop()
    // "For an immediate stop, use pause(), followed by flush() to discard audio data that hasn't been played back yet.

    // found a similar issue here:
    // https://stackoverflow.com/questions/22422234/audiotrack-flush-causing-static
    private fun stopAllTonesForRestart() {
        toneTracks.values.forEach { track ->
            if (track.playState == AudioTrack.PLAYSTATE_PLAYING) {
                //track.pause()
                track.stop()
            }
            track.flush()
            track.playbackHeadPosition = 0
        }
    }

    private fun stopAllTonesNow() {
        toneTracks.values.forEach { track ->
            if (track.playState == AudioTrack.PLAYSTATE_PLAYING) {
                //track.pause()
                track.stop()
            }
            track.flush()
            track.playbackHeadPosition = 0
        }
    }

    private fun buildToneTracks(): Map<Char, AudioTrack> {
        return mapOf(
            'R' to createToneTrack(261.63),
            'G' to createToneTrack(293.66),
            'B' to createToneTrack(329.63),
            'M' to createToneTrack(392.00),
            'Y' to createToneTrack(440.00),
            'C' to createToneTrack(523.25),
        )
    }

    private fun createToneTrack(frequencyHz: Double): AudioTrack {
        val buffer = generateToneBuffer(
            frequencyHz = frequencyHz,
            durationMs = TONE_DURATION_MS,
            sampleRate = TONE_SAMPLE_RATE
        )
        val minSize = AudioTrack.getMinBufferSize(
            TONE_SAMPLE_RATE,
            AudioFormat.CHANNEL_OUT_MONO,
            AudioFormat.ENCODING_PCM_16BIT
        )
        val bufferBytes = buffer.size * 2
        val safeMinSize = if (minSize > 0) minSize else bufferBytes
        val format = AudioFormat.Builder()
            .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
            .setSampleRate(TONE_SAMPLE_RATE)
            .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
            .build()
        val track = AudioTrack.Builder()
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_GAME)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build()
            )
            .setAudioFormat(format)
            .setTransferMode(AudioTrack.MODE_STATIC)
            .setBufferSizeInBytes(2*max(bufferBytes, safeMinSize))
            .build()
        track.write(buffer, 0, buffer.size)
        return track
    }

    private fun generateToneBuffer(
        frequencyHz: Double,
        durationMs: Int,
        sampleRate: Int
    ): ShortArray {
        // number of pcm samples for durationMs at the given sampleRate
        // example: 240ms at 44100 Hz -> 0.240 * 44100 ≈ 10584 samples
        val totalSamples = ((durationMs / 1000.0) * sampleRate).toInt().coerceAtLeast(1)

        // fade in and fade out length in samples to reduce clicks at start and end
        // 0.02s == 20ms, clamped so fades never exceed half of the buffer
        val fadeSamples = (sampleRate * 0.04).toInt().coerceAtLeast(1).coerceAtMost(totalSamples / 2)

        // precompute 2πf so inside the loop only multiply by time
        val twoPiF = 2.0 * Math.PI * frequencyHz

        // 16-bit mono pcm buffer, values will be in [-32768, 32767]
        val buffer = ShortArray(totalSamples)

        for (i in 0 until totalSamples) {
            // time of this sample in seconds
            val t = i.toDouble() / sampleRate

            // base amplitude to avoid clipping
            var amplitude = 0.35

            // apply a simple fade at the start and end
            // smooth volume ramp/descent over time
            if (i < fadeSamples) {
                amplitude *= i.toDouble() / fadeSamples
            } else if (i > totalSamples - fadeSamples) {
                amplitude *= (totalSamples - i).toDouble() / fadeSamples
            }

            // generate sine wave and scale to 16-bit range
            val sample = (sin(twoPiF * t) * amplitude * Short.MAX_VALUE).toInt()
            buffer[i] = sample.toShort()
        }

        return buffer
    }

    private fun saveStateToSavedHandle() {
        savedStateHandle[KEY_GAME_SEQUENCE] = gameSequence.joinToString(separator = "")
        savedStateHandle[KEY_USER_SEQUENCE] = userSequence.joinToString(separator = "")
        savedStateHandle[KEY_CURRENT_STEP] = currentStep
        savedStateHandle[KEY_IS_GAME_ACTIVE] = isGameActive
        savedStateHandle[KEY_IS_GAME_PAUSED] = isGamePaused
        savedStateHandle[KEY_IS_PRESENTING_SEQUENCE] = isPresentingSequence
        savedStateHandle[KEY_PRESENTATION_STEP] = presentationStep
        savedStateHandle[KEY_FAILED] = failed
    }

    // restore sequences and flags from saved state handle after process death
    private fun restoreStateFromSavedHandle() {
        val restoredGameSequence = savedStateHandle.get<String>(KEY_GAME_SEQUENCE).orEmpty()
        val restoredUserSequence = savedStateHandle.get<String>(KEY_USER_SEQUENCE).orEmpty()
        val restoredCurrentStep = savedStateHandle.get<Int>(KEY_CURRENT_STEP) ?: 0
        val restoredIsGameActive = savedStateHandle.get<Boolean>(KEY_IS_GAME_ACTIVE) ?: false
        val restoredIsGamePaused = savedStateHandle.get<Boolean>(KEY_IS_GAME_PAUSED) ?: false
        val restoredWasPresenting = savedStateHandle.get<Boolean>(KEY_IS_PRESENTING_SEQUENCE) ?: false
        val restoredPresentationStep = savedStateHandle.get<Int>(KEY_PRESENTATION_STEP) ?: 0
        val restoredFailed = savedStateHandle.get<Boolean>(KEY_FAILED) ?: false

        gameSequence.clear()
        gameSequence.addAll(restoredGameSequence.toList())
        userSequence.clear()
        userSequence.addAll(restoredUserSequence.toList())

        val maxStep = (gameSequence.size - 1).coerceAtLeast(0)
        currentStep = restoredCurrentStep.coerceIn(0, maxStep)
        val totalSteps = gameSequence.size * 2
        presentationStep = restoredPresentationStep.coerceIn(0, totalSteps)

        isGameActive = restoredIsGameActive
        isGamePaused = restoredIsGamePaused
        failed = restoredFailed
        highlightedChar = null
        pauseFlow.value = isGamePaused
        isNavigatingToScore = false

        // rewind to last highlight step so resume replays the last lit tile
        val adjustedStartStep = when {
            totalSteps == 0 -> 0
            presentationStep >= totalSteps -> totalSteps
            presentationStep % 2 == 1 -> (presentationStep - 1).coerceAtLeast(0)
            else -> presentationStep
        }
        presentationStep = adjustedStartStep

        // resume presentation only when the last run was mid-playback
        if (restoredWasPresenting && isGameActive && !failed && gameSequence.isNotEmpty() && presentationStep < totalSteps) {
            presentSequence(presentationStep, RESUME_PRESENTATION_DELAY_MS)
        } else {
            isPresentingSequence = false
            saveStateToSavedHandle()
        }
    }
}

@Composable
fun GameScreen(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    // intercept back to finish the game and navigate to score screen
    // prevents the default nav back stack pop while a run is active
    BackHandler {
        onNavigateToScore()
    }

    val configuration = LocalConfiguration.current

    when (configuration.orientation) {
        Configuration.ORIENTATION_LANDSCAPE -> {
            LandscapeLayout(modifier, viewModel, onNavigateToScore)
        }
        else -> {
            PortraitLayout(modifier, viewModel, onNavigateToScore)
        }
    }
}

@Composable
fun PortraitLayout(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    Column(modifier = modifier.fillMaxSize()) {
        Title(
            modifier = Modifier
                .wrapContentHeight()
                .align(Alignment.CenterHorizontally),
            text = stringResource(R.string.app_name)
        )
        GameMatrix(Modifier.weight(4f), viewModel)
        SequenceDisplay(Modifier.weight(1f), viewModel)
        GameButtons(Modifier.wrapContentHeight(), viewModel, onNavigateToScore)
    }
}

@Composable
fun LandscapeLayout(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Title(
            modifier = Modifier
                .align(Alignment.CenterHorizontally)
                .wrapContentHeight(),
            text = stringResource(R.string.app_name)
        )

        Row(
            modifier = modifier.fillMaxWidth(),
        ) {
            GameMatrix(Modifier.weight(1f), viewModel)

            Column(modifier = Modifier.weight(1f)) {
                SequenceDisplay(Modifier.weight(1f), viewModel)
                GameButtons(Modifier.wrapContentHeight(), viewModel, onNavigateToScore)
            }
        }
    }
}

@Composable
fun GameMatrix(modifier: Modifier = Modifier, viewModel: GameViewModel) {
    Column(modifier = modifier.fillMaxWidth().padding(horizontal = 8.dp)) {
        Row(modifier = Modifier.weight(1f)) {
            ColorButton(Color.Red, 'R', Modifier.weight(1f), viewModel)
            ColorButton(Color.Green, 'G', Modifier.weight(1f), viewModel)
        }
        Row(modifier = Modifier.weight(1f)) {
            ColorButton(Color.Blue, 'B', Modifier.weight(1f), viewModel)
            ColorButton(Color.Magenta, 'M', Modifier.weight(1f), viewModel)
        }
        Row(modifier = Modifier.weight(1f)) {
            ColorButton(Color.Yellow, 'Y', Modifier.weight(1f), viewModel)
            ColorButton(Color.Cyan, 'C', Modifier.weight(1f), viewModel)
        }
    }
}

@Composable
fun ColorButton(color: Color, char: Char, modifier: Modifier, viewModel: GameViewModel) {
    val isLit = viewModel.highlightedChar == char
    val shownColor = if (isLit) lerp(color, Color.White, 0.45f) else color

    Button(
        onClick = {
            viewModel.onColorPressed(char)
        },
        colors = ButtonDefaults.buttonColors(shownColor),
        shape = RectangleShape,
        modifier = modifier
            .fillMaxHeight()
            .padding(4.dp)
    ) {
    }
}

@Composable
fun SequenceDisplay(modifier: Modifier = Modifier, viewModel: GameViewModel) {
    val scrollState = rememberScrollState()
    val showProgress by remember {
        derivedStateOf { scrollState.maxValue > 0 }
    }

    Column(modifier = modifier.fillMaxWidth()) {
        Text(
            text = stringResource(R.string.sequence_text_game_screen),
            modifier = Modifier
                .padding(horizontal = 24.dp)
                .padding(top = 8.dp)
        )
        Column(
            modifier = Modifier
                .padding(horizontal = 24.dp, vertical = 8.dp)
                .border(1.dp, Color(0xFFBDBDBD), RoundedCornerShape(8.dp))
                .padding(8.dp)
                .heightIn(max = 160.dp)
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f, fill = false)
                    .verticalScroll(scrollState)
            ) {
                Text(
                    text = viewModel.getUserSequence().joinToString(separator = ", "),
                    modifier = Modifier.fillMaxWidth()
                )
            }

            if (showProgress) {
                LinearProgressIndicator(
                    progress = {
                        val max = scrollState.maxValue
                        if (max == 0) 0f else (scrollState.value.toFloat() / max).coerceIn(0f, 1f)
                    },
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 8.dp),
                )
            }
        }
        if (viewModel.failed) {
            Text(
                text = stringResource(R.string.game_failed_text_game_screen),
                color = Color.Red,
                modifier = Modifier
                    .padding(horizontal = 24.dp)
                    .padding(bottom = 8.dp)
            )
        }
    }
}

@Composable
fun GameButtons(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    Row(modifier = modifier.padding(16.dp)) {
        Button(
            onClick = {
                viewModel.startGame()
            },
            modifier = Modifier.weight(1f).padding(end = 8.dp),
            enabled = !viewModel.isGameActive && !viewModel.failed
        ) {
            Text(stringResource(R.string.start_game_button_game_screen))
        }

        Button(
            onClick = {
                if (viewModel.isGamePaused) viewModel.resumeGame() else viewModel.pauseGame()
            },
            modifier = Modifier.weight(1f).padding(horizontal = 8.dp),
            enabled = viewModel.isGameActive && !viewModel.failed && viewModel.isPresentingSequence
        ) {
            if (viewModel.isGamePaused) Text(stringResource(R.string.resume_button_game_screen))
            else Text(stringResource(R.string.pause_button_game_screen))
        }

        Button(
            onClick = {
                onNavigateToScore()
            },
            modifier = Modifier.weight(1f).padding(start = 8.dp),
            enabled = viewModel.isGameActive && !viewModel.failed
        ) {
            Text(stringResource(R.string.finish_game_button))
        }
    }
}
