package com.example.simon

import android.app.Application
import android.content.res.Configuration
import androidx.activity.compose.BackHandler
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.wrapContentHeight
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlin.math.min

sealed interface GameNavigationEvent {
    data object NavigateToScore : GameNavigationEvent
}

class GameViewModel(application: Application, private val savedStateHandle: SavedStateHandle) : AndroidViewModel(application) {
    // shared repository used to save completed games
    private val scoreRepository = (application as SimonApplication).scoreRepository

    // mutable sequences for current run:
    // - gameSequence: expected sequence generated by the app
    // - userSequence: sequence entered by the player
    private val userSequence = mutableStateListOf<Char>()
    private val gameSequence = mutableStateListOf<Char>()

    // index of the next expected character in gameSequence
    private var currentStep = 0

    // guard to avoid multiple concurrent navigation/save requests
    private var isNavigatingToScore = false

    // UI-observed state flags
    var isGameActive by mutableStateOf(false)
    var isGamePaused by mutableStateOf(false)
    var isPresentingSequence by mutableStateOf(false)
    var failed by mutableStateOf(false)

    // currently highlighted tile while presenting the sequence
    var highlightedChar by mutableStateOf<Char?>(null)

    // pauseFlow controls pause/resume
    // playbackJob runs sequence animation
    private val pauseFlow = MutableStateFlow(false)
    private var playbackJob: Job? = null

    // internal event bus for one-off navigation events
    private val _navigationEvents = MutableSharedFlow<GameNavigationEvent>(extraBufferCapacity = 1)
    val navigationEvents: SharedFlow<GameNavigationEvent> = _navigationEvents.asSharedFlow()

    companion object {
        private const val KEY_GAME_SEQUENCE = "game_sequence"
        private const val KEY_USER_SEQUENCE = "user_sequence"
        private const val KEY_CURRENT_STEP = "current_step"
        private const val KEY_IS_GAME_ACTIVE = "is_game_active"
        private const val KEY_IS_GAME_PAUSED = "is_game_paused"
        private const val KEY_IS_PRESENTING_SEQUENCE = "is_presenting_sequence"
        private const val KEY_FAILED = "failed"
    }

    init {
        restoreStateFromSavedHandle()
    }

    // read-only copies exposed to UI/composables
    fun getGameSequence(): List<Char> = gameSequence.toList()
    fun getUserSequence(): List<Char> = userSequence.toList()

    // starts a new run from a clean state and immediately presents round 1
    fun startGame() {
        currentStep = 0
        userSequence.clear()
        gameSequence.clear()
        isGameActive = true
        isPresentingSequence = true
        failed = false
        isGamePaused = false
        isNavigatingToScore = false
        resumeGame()
        nextRound()
    }

    // resets all gameplay state when leaving/restarting the game screen
    fun reset() {
        gameSequence.clear()
        userSequence.clear()
        stopPresentation()
        currentStep = 0
        isGameActive = false
        isGamePaused = false
        isPresentingSequence = false
        failed = false
        isNavigatingToScore = false
        saveStateToSavedHandle()
    }

    // handles a tile press from the player
    // correct  -> advance step/round
    // wrong    -> mark game as failed
    fun onColorPressed(char: Char) {
        if (!isGameActive || failed || isGamePaused || isPresentingSequence) {
            return
        }

        userSequence.add(char)
        if (isExpectedInput(char)) {
            currentStep++
            if (userSequence.size == gameSequence.size) {
                currentStep = 0
                userSequence.clear()
                nextRound()
            } else {
                saveStateToSavedHandle()
            }
            return
        }

        isGameActive = false
        failed = true
        saveStateToSavedHandle()
    }

    // called when user wants to leave game and go to score screen
    // saves a valid score (if available) and emits navigation event
    fun requestNavigateToScore() {
        if (isNavigatingToScore) return
        isNavigatingToScore = true

        val score = buildScoreForCurrentGame()
        viewModelScope.launch {
            if (score != null) {
                scoreRepository.saveScore(score)
                userSequence.clear()
                saveStateToSavedHandle()
            }
            _navigationEvents.emit(GameNavigationEvent.NavigateToScore)
        }
    }

    // builds a score snapshot for the current run
    // returns null when the run is not in a state that should be saved
    private fun buildScoreForCurrentGame(): Score? {
        if (!isGameActive && !failed) return null
        if (isPresentingSequence && gameSequence.size == 1) return null
        if (gameSequence.isEmpty()) return null

        return Score(
            playedGameSequence = gameSequence.toList(),
            playedUserSequence = userSequence.toList(),
            maxCorrectSequence = (gameSequence.size - 1).coerceAtLeast(0),
            errorPosition = currentStep.coerceIn(0, gameSequence.size)
        )
    }

    private fun isExpectedInput(char: Char): Boolean {
        val expectedChar = gameSequence.getOrNull(currentStep) ?: return false
        return char == expectedChar
    }

    private fun nextRound() {
        gameSequence.add(generateGameCharacter())
        saveStateToSavedHandle()
        presentSequence()
    }

    private fun generateGameCharacter(): Char {
        return when ((1..6).random()) {
            1 -> 'R'
            2 -> 'G'
            3 -> 'B'
            4 -> 'M'
            5 -> 'Y'
            else -> 'C'
        }
    }

    fun pauseGame() {
        isGamePaused = true
        pauseFlow.value = true
        saveStateToSavedHandle()
    }

    fun resumeGame() {
        isGamePaused = false
        pauseFlow.value = false
        saveStateToSavedHandle()
    }

    private fun stopPresentation() {
        playbackJob?.cancel()
        highlightedChar = null
        isPresentingSequence = false
        saveStateToSavedHandle()
    }

    private fun presentSequence() {
        playbackJob?.cancel()
        playbackJob = viewModelScope.launch {
            isPresentingSequence = true
            saveStateToSavedHandle()
            try {
                for (c in gameSequence) {
                    awaitIfPaused()

                    highlightedChar = c
                    pauseAwareDelay(450)

                    highlightedChar = null
                    pauseAwareDelay(150)
                }
            } finally {
                highlightedChar = null
                isPresentingSequence = false
                saveStateToSavedHandle()
            }
        }
    }

    private suspend fun awaitIfPaused() {
        pauseFlow.filter { paused -> !paused }.first()
    }

    private suspend fun pauseAwareDelay(totalMs: Long) {
        var remaining = totalMs
        while (remaining > 0) {
            awaitIfPaused()
            val step = min(remaining, 16L)
            delay(step)
            if (!pauseFlow.value) remaining -= step
        }
    }

    private fun saveStateToSavedHandle() {
        savedStateHandle[KEY_GAME_SEQUENCE] = gameSequence.joinToString(separator = "")
        savedStateHandle[KEY_USER_SEQUENCE] = userSequence.joinToString(separator = "")
        savedStateHandle[KEY_CURRENT_STEP] = currentStep
        savedStateHandle[KEY_IS_GAME_ACTIVE] = isGameActive
        savedStateHandle[KEY_IS_GAME_PAUSED] = isGamePaused
        savedStateHandle[KEY_IS_PRESENTING_SEQUENCE] = isPresentingSequence
        savedStateHandle[KEY_FAILED] = failed
    }

    // if the presentation was in the middle of showing the sequence
    // the whole sequence will be shown again
    private fun restoreStateFromSavedHandle() {
        val restoredGameSequence = savedStateHandle.get<String>(KEY_GAME_SEQUENCE).orEmpty()
        val restoredUserSequence = savedStateHandle.get<String>(KEY_USER_SEQUENCE).orEmpty()
        val restoredCurrentStep = savedStateHandle.get<Int>(KEY_CURRENT_STEP) ?: 0
        val restoredIsGameActive = savedStateHandle.get<Boolean>(KEY_IS_GAME_ACTIVE) ?: false
        val restoredIsGamePaused = savedStateHandle.get<Boolean>(KEY_IS_GAME_PAUSED) ?: false
        val restoredWasPresenting = savedStateHandle.get<Boolean>(KEY_IS_PRESENTING_SEQUENCE) ?: false
        val restoredFailed = savedStateHandle.get<Boolean>(KEY_FAILED) ?: false

        gameSequence.clear()
        gameSequence.addAll(restoredGameSequence.toList())
        userSequence.clear()
        userSequence.addAll(restoredUserSequence.toList())

        val maxStep = (gameSequence.size - 1).coerceAtLeast(0)
        currentStep = restoredCurrentStep.coerceIn(0, maxStep)

        isGameActive = restoredIsGameActive
        isGamePaused = restoredIsGamePaused
        failed = restoredFailed
        highlightedChar = null
        pauseFlow.value = isGamePaused
        isNavigatingToScore = false

        if (restoredWasPresenting && isGameActive && !failed && gameSequence.isNotEmpty()) {
            presentSequence()
        } else {
            isPresentingSequence = false
            saveStateToSavedHandle()
        }
    }
}

@Composable
fun GameScreen(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    BackHandler {
        onNavigateToScore()
    }

    val configuration = LocalConfiguration.current

    when (configuration.orientation) {
        Configuration.ORIENTATION_LANDSCAPE -> {
            LandscapeLayout(modifier, viewModel, onNavigateToScore)
        }
        else -> {
            PortraitLayout(modifier, viewModel, onNavigateToScore)
        }
    }
}

@Composable
fun PortraitLayout(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    Column(modifier = modifier.fillMaxSize()) {
        Title(
            modifier = Modifier
                .wrapContentHeight()
                .align(Alignment.CenterHorizontally),
            text = stringResource(R.string.app_name)
        )
        GameMatrix(Modifier.weight(4f), viewModel)
        SequenceDisplay(Modifier.weight(1f), viewModel)
        GameButtons(Modifier.wrapContentHeight(), viewModel, onNavigateToScore)
    }
}

@Composable
fun LandscapeLayout(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Title(
            modifier = Modifier
                .align(Alignment.CenterHorizontally)
                .wrapContentHeight(),
            text = stringResource(R.string.app_name)
        )

        Row(
            modifier = modifier.fillMaxWidth(),
        ) {
            GameMatrix(Modifier.weight(1f), viewModel)

            Column(modifier = Modifier.weight(1f)) {
                SequenceDisplay(Modifier.weight(1f), viewModel)
                GameButtons(Modifier.wrapContentHeight(), viewModel, onNavigateToScore)
            }
        }
    }
}

@Composable
fun GameMatrix(modifier: Modifier = Modifier, viewModel: GameViewModel) {
    Column(modifier = modifier.fillMaxWidth().padding(horizontal = 8.dp)) {
        Row(modifier = Modifier.weight(1f)) {
            ColorButton(Color.Red, 'R', Modifier.weight(1f), viewModel)
            ColorButton(Color.Green, 'G', Modifier.weight(1f), viewModel)
        }
        Row(modifier = Modifier.weight(1f)) {
            ColorButton(Color.Blue, 'B', Modifier.weight(1f), viewModel)
            ColorButton(Color.Magenta, 'M', Modifier.weight(1f), viewModel)
        }
        Row(modifier = Modifier.weight(1f)) {
            ColorButton(Color.Yellow, 'Y', Modifier.weight(1f), viewModel)
            ColorButton(Color.Cyan, 'C', Modifier.weight(1f), viewModel)
        }
    }
}

@Composable
fun ColorButton(color: Color, char: Char, modifier: Modifier, viewModel: GameViewModel) {
    val isLit = viewModel.highlightedChar == char
    val shownColor = if (isLit) lerp(color, Color.White, 0.45f) else color

    Button(
        onClick = {
            viewModel.onColorPressed(char)
        },
        colors = ButtonDefaults.buttonColors(shownColor),
        shape = RectangleShape,
        modifier = modifier
            .fillMaxHeight()
            .padding(4.dp)
    ) {
    }
}

@Composable
fun SequenceDisplay(modifier: Modifier = Modifier, viewModel: GameViewModel) {
    val scrollState = rememberScrollState()
    val showProgress by remember {
        derivedStateOf { scrollState.maxValue > 0 }
    }

    Column(modifier = modifier.fillMaxWidth()) {
        Text(
            text = stringResource(R.string.sequence_text_game_screen, viewModel.getUserSequence().joinToString(separator = ", ")),
            modifier = Modifier
                .padding(24.dp)
                .verticalScroll(scrollState)
                .fillMaxWidth(),
        )

        if (showProgress) {
            LinearProgressIndicator(
                progress = {
                    val max = scrollState.maxValue
                    if (max == 0) 0f else (scrollState.value.toFloat() / max).coerceIn(0f, 1f)
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp)
                    .padding(bottom = 8.dp),
            )
        }
    }
}

@Composable
fun GameButtons(modifier: Modifier = Modifier, viewModel: GameViewModel, onNavigateToScore: () -> Unit) {
    Row(modifier = modifier.padding(16.dp)) {
        Button(
            onClick = {
                viewModel.startGame()
            },
            modifier = Modifier.weight(1f).padding(end = 8.dp),
            enabled = !viewModel.isGameActive && !viewModel.failed
        ) {
            Text(stringResource(R.string.start_game_button_game_screen))
        }

        Button(
            onClick = {
                if (viewModel.isGamePaused) viewModel.resumeGame() else viewModel.pauseGame()
            },
            modifier = Modifier.weight(1f).padding(horizontal = 8.dp),
            enabled = viewModel.isGameActive && !viewModel.failed && viewModel.isPresentingSequence
        ) {
            if (viewModel.isGamePaused) Text(stringResource(R.string.resume_button_game_screen))
            else Text(stringResource(R.string.pause_button_game_screen))
        }

        Button(
            onClick = {
                onNavigateToScore()
            },
            modifier = Modifier.weight(1f).padding(start = 8.dp),
            enabled = viewModel.isGameActive && !viewModel.failed
        ) {
            Text(stringResource(R.string.finish_game_button))
        }
    }
}
